import random 
# Function to generate a random number between 1 and 100 
def roll (): 
    min_value= 1 
    max_value= 6 
    roll = random.randint(min_value, max_value)
# random.randint() generates a random integer between the two specified values
    # return the generated random number
    # tab provides auto-completion for the function
    return roll

value = roll() # Call the roll function to get a random number
print (value) # Print the random number generated by the roll function

while True:
    players = input("Enter the number of players (1-4): ")
    # Loop until a valid number of players is entered
    # Validate the number of players input
    if players.isdigit():
        #isdigit() checks if the input is a digit
        #if statement checks if the statement is true 
        players = int(players)
        if 1 <= players <= 4:
            break
        # break keyword exits the loop if a valid number is entered, exit the wall loop 
        else:
            # else block handles invalid input, if the if statement is false, else block executes
            print("Invalid number of players. Please enter a number between 1 and 4.")
    else:
            print("Invalid, try again.") 
    # If the input is not a digit, prompt the user again
    # The problem is caused by incorrect indentation of the `else:` statement; it should align with its corresponding `if` statement.


print(players) # Print the number of players

#9:40 https://www.youtube.com/watch?v=21FnnGKSRZo&t=132s


